version: 2
jobs:
  reticulate:
    docker:
      - image: condaforge/mambaforge:4.10.3-1
    environment:
      NOT_CRAN: true
      R_LIBS: ~/R/Library
    steps:
      - checkout
      - run:
          name: Configure conda
          command: |
            conda config --set always_yes yes
            conda config --set quiet yes
            conda config --set changeps1 no
            conda config --set auto_update_conda no
      - run:
          name: Install
          command: |
            mamba update --all
            mamba install git \
                          matplotlib \
                          qpdf \
                          r-base \
                          r-clipr \
                          r-devtools \
                          r-miniui \
                          r-recommended \
                          r-reticulate \
                          r-shiny \
                          r-testthat \
                          r-withr \
                          r-workflowr \
                          xorg-libsm \
                          xorg-libxt
      - run:
          name: Clone workflowr
          command: git clone https://github.com/workflowr/workflowr.git ../workflowr
      - run:
          name: Build and install workflowr
          command: |
            mkdir -p ~/R/Library
            R CMD build --no-build-vignettes --no-manual ../workflowr
            R CMD INSTALL workflowr_*tar.gz
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'library(workflowr); devtools::session_info()'
            conda list
      - run:
          name: Test wflow_html() with reticulate >= 1.15
          command: Rscript -e 'devtools::test(pkg = "../workflowr", filter = "html$")'
      - run:
          name: Install reticulate 1.14
          command: mamba install r-reticulate==1.14
      - run:
          name: Test wflow_html() with reticulate == 1.14
          command: Rscript -e 'devtools::test(pkg = "../workflowr", filter = "html$")'
  speed:
    docker:
      - image: rocker/r-base:latest
    environment:
      PANDOC: 2.7
      R_LIBS: ~/R/Library
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-v7-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-v7-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-
      - checkout
      - run:
          name: Install system dependencies
          command: bash scripts/install-system.sh
      - run:
          name: Install pandoc
          command: bash scripts/install-pandoc.sh $PANDOC
      - run:
          name: Clone workflowr
          command: git clone https://github.com/workflowr/workflowr.git /tmp/workflowr/
      - run:
          name: Install package dependencies
          command: |
            mkdir -p ~/R/Library
            Rscript -e 'install.packages("stringi")'
            Rscript scripts/install-r-pkgs.R
      - run:
          name: Install bench package
          command: Rscript -e 'install.packages("bench")'
      - run:
          name: Install workflowr 1.4.0
          command: Rscript -e 'remotes::install_version("workflowr", "1.4.0")'
      - run:
          name: Record speed of workflowr 1.4.0
          command: Rscript scripts/speed-test.R
      - run:
          name: Install workflowr from CRAN
          command: Rscript -e 'install.packages("workflowr")'
      - run:
          name: Record speed of workflowr from CRAN
          command: Rscript scripts/speed-test.R
      - run:
          name: Install workflowr dev
          command: R CMD INSTALL --build /tmp/workflowr/
      - run:
          name: Record speed of workflowr dev
          command: Rscript scripts/speed-test.R
      - run:
          name: Clone git2r
          command: git clone https://github.com/ropensci/git2r.git /tmp/git2r/
      - run:
          name: Install git2r dev
          command: R CMD INSTALL --build /tmp/git2r/
      - run:
          name: Record speed of workflowr dev with git2r dev
          command: Rscript scripts/speed-test.R
      - save_cache:
          key: r-pkg-cache-v7-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"

workflows:
  version: 2
  # commit:
  #   jobs:
  #     - reticulate
  #     - speed
  # weekly:
  #   triggers:
  #     - schedule:
  #         # "At 09:00 on Monday."
  #         # https://crontab.guru/#0_09_*_*_1
  #         cron: "0 09 * * 1"
  #         filters:
  #           branches:
  #             only:
  #               - main
  #   jobs:
  #     - reticulate
  #     - speed
