version: 2
jobs:
  future:
    docker:
      - image: rocker/r-ver:devel
    environment:
      NOT_CRAN: true
      R_LIBS: ~/R/Library
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install --yes --no-install-recommends \
              git \
              libgit2-dev \
              libssl-dev \
              pandoc \
              pandoc-citeproc \
              zlib1g-dev
      - run:
          name: Clone workflowr
          command: git clone https://github.com/jdblischak/workflowr.git
      - run:
          name: Install package dependencies from GitHub
          command: |
            mkdir -p ~/R/Library
            Rscript -e 'install.packages("remotes")'
            Rscript -e 'remotes::install_github("r-lib/processx")'
            Rscript -e 'remotes::install_github("r-lib/callr")'
            Rscript -e 'remotes::install_github("r-lib/fs")'
            Rscript -e 'remotes::install_github("wrathematics/getPass")'
            Rscript -e 'remotes::install_github("ropensci/git2r")'
            Rscript -e 'remotes::install_github("tidyverse/glue")'
            Rscript -e 'remotes::install_github("r-lib/httr")'
            Rscript -e 'remotes::install_github("yihui/knitr")'
            Rscript -e 'remotes::install_github("rstudio/rmarkdown")'
            Rscript -e 'remotes::install_github("r-lib/rprojroot")'
            Rscript -e 'remotes::install_github("rstudio/rstudioapi")'
            Rscript -e 'remotes::install_github("tidyverse/stringr")'
            Rscript -e 'remotes::install_github("edwindj/whisker")'
            Rscript -e 'remotes::install_github("viking/r-yaml")'
            Rscript -e 'remotes::install_github("mdlincoln/clipr")'
            Rscript -e 'remotes::install_github("r-lib/covr")'
            Rscript -e 'remotes::install_github("r-lib/devtools")'
            Rscript -e 'remotes::install_github("rstudio/miniUI")'
            Rscript -e 'remotes::install_github("rstudio/shiny")'
            Rscript -e 'remotes::install_github("ropensci/spelling")'
            Rscript -e 'remotes::install_github("r-lib/testthat")'
            Rscript -e 'remotes::install_github("r-lib/withr")'
            Rscript -e 'remotes::install_github("jdblischak/workflowr")'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'library(workflowr); devtools::session_info()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build and check package
          command: |
            cd workflowr
            bash build.sh
      - store_artifacts:
          path: workflowr/workflowr-pkg-tests.Rcheck/
      - save_cache:
          key: r-pkg-cache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"

workflows:
  version: 2
  all:
    jobs:
      - future
