name: wflow-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Depends:
  - r-base >= 3.3.0
  # Imports:
  - r-callr >= 3.7.0
  - r-fs >= 1.2.7
  - r-getPass
  - r-git2r >= 0.26.0
  - r-glue
  - r-httpuv >= 1.2.2
  - r-httr
  - r-knitr >= 1.29
  - r-rmarkdown >= 1.18
  - r-rprojroot >= 1.2
  - r-rstudioapi >= 0.6
  - r-stringr >= 1.3.0
  - r-whisker >= 0.3-2
  - r-xfun
  - r-yaml
  # Suggests:
  - r-clipr >= 0.7.0
  - r-miniUI >= 0.1.1
  - r-reticulate >= 1.15
  - r-sessioninfo
  - r-shiny >= 0.14
  - r-testthat >= 2.0.0
  - r-withr >= 2.0.0
  # SystemRequirements:
  - pandoc >= 1.14, < 3
  # Extras
  - r-codetools
