name: spell-check
on:
  schedule: # quarterly
    - cron: "0 09 1 */3 *"
  workflow_dispatch:
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    name: spell-check
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "workflowr/workflowr"
      - name: Setup r2u
        uses: eddelbuettel/github-actions/r2u-setup@master
        with:
          bspm-version-check: "FALSE"
      - name: Install dependencies
        run: |
          apt-get install --yes \
            r-cran-spelling
        shell: sudo bash {0}
      - name: Spell check
        run: |
          library("spelling")
          typos <- spell_check_package()
          if (nrow(typos)) {
            print(typos)
            stop("")
          } else {
            message("No typos detected!!")
          }
        shell: Rscript {0}
