name: update-conda-lockfiles
on:
  schedule: # quarterly
    - cron: "0 09 1 */3 *"
  push:
    paths:
      - 'conda/environment.yaml'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  lock:
    runs-on: ${{ matrix.config.os }}
    name: lock-${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-13, slug: 'macos', shell: 'bash -l {0}'}
          - {os: ubuntu-22.04, slug: 'linux', shell: 'bash -l {0}'}
          - {os: windows-2022, slug: 'win', shell: 'cmd /C CALL {0}'}
    defaults:
      run:
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            use-mamba: true
            environment-file: conda/environment.yaml
            activate-environment: wflow-env
      - name: Export lockfile
        run: conda list --explicit --md5 > conda/environment-${{ matrix.config.slug }}.lock
      - name: Diff lockfile
        run: git diff
      - name: Commit lockfile
        if: github.ref == 'refs/heads/main' && github.repository == 'workflowr/workflowr-pkg-tests'
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "runneradmin@github.com"
          git pull origin main
          git add conda/environment-${{ matrix.config.slug }}.lock
          git commit --allow-empty -m "Update lockfile for ${{ matrix.config.slug }}"
          git push origin main
